name: Build Android APK (Buildozer)

on:
  workflow_dispatch:   # lets you run manually
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Buildozer in Docker
        uses: addnab/docker-run-action@v3
        with:
          image: kivy/buildozer:latest
          options: --privileged
          run: |
            pip install --upgrade buildozer cython
            buildozer android clean || true
            buildozer -v android debug
            mkdir -p /github/workspace/apk_out
            cp -v bin/*.apk /github/workspace/apk_out/ || true

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SpeechTranslator-APK
          path: apk_out/*.apk
