name: Build Android APK (Buildozer - docker)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build with Buildozer (Docker container)
        uses: docker://kivy/buildozer:python3
        with:
          entrypoint: /bin/sh
          args: -c "pip install --upgrade buildozer cython && buildozer android clean || true && buildozer -v android debug || true && mkdir -p /github/workspace/apk_out && cp -v bin/*.apk /github/workspace/apk_out/ || true"

      - name: List produced files (debug)
        run: ls -la apk_out || true

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: SpeechTranslator-APK
          path: apk_out/*.apk
